### ISSUE TITLE
Starting date of forcing data

### ISSUE THREAD

**Issue by Cheng168** [peterson-tim-j/HydroSight#19]
It appears that the model requires forcing data to have starting date a few years earlier than the stating date of obshead. I tried forcing data with different starting dates. The one with 10 years worked, but the one with 5 years didn't. Not sure what the minimum is.  Cheers, Xiang

**Comment by Cheng168** [comment]
Tim, I reported this bug last year in an early version. It no long exists in version 1.29 and later.

**Comment by peterson-tim-j** [comment]
Bug resolved in V1.30,
