### ISSUE TITLE
Climate only model tutorial - model calib screen shot

### ISSUE THREAD

**Issue by peterson-tim-j** [peterson-tim-j/HydroSight#29]
![screenshot from 2018-04-19 20-43-15](https://user-images.githubusercontent.com/8623994/38987464-3a4ec5c0-4413-11e8-98ed-d37ae05da0f3.png)

**Comment by KongFeihe** [comment]
@peterson-tim-j The above HydroSight Model Calibration window has not shown after I select the left checkbox. So the settings for calibration method didn't occur, and it ran the calibration directly. What should I do to address this problems, can you give me some suggestions? Thanks.

**Comment by peterson-tim-j** [comment]
Nice to see my wiki documentation is already being looked at (I assume you were looking at https://github.com/peterson-tim-j/HydroSight/wiki/Climate-only-TFN-model-tutorial). The screenshot you shown is a feature only available in v1.29. You can access it by running HydroSight using the newest source code from within MatLab. If you don't have access then I'll be releasing a compiled v1.29 in a few weeks.

**Comment by KongFeihe** [comment]
Thank you so much. You mean only the programmatic interface can conduct the settings.  I don't have access to MatLab, I am looking forward to your compiled v1.29.
