### ISSUE TITLE
Climate only model tutorial - model calib forcing screen shot

### ISSUE THREAD

**Issue by peterson-tim-j** [peterson-tim-j/HydroSight#31]
![screenshot from 2018-04-19 21-14-11](https://user-images.githubusercontent.com/8623994/38989396-1afc37a0-441a-11e8-8bbc-d04d99b3a022.png)

**Comment by KongFeihe** [comment]
The pop-up Warning Dialog is open when I place the cursor in Model Options, just as the below screenshot 1. I don't know where is the problem, the format of the dataset meet the requirement (screenshot 2).
![1](https://user-images.githubusercontent.com/38413487/40092922-6ec0c032-58af-11e8-9360-20e3ad170114.png)
![2](https://user-images.githubusercontent.com/38413487/40093149-5a4756ec-58b0-11e8-8faa-a2a10c405ed4.png)

**Comment by peterson-tim-j** [comment]
Thanks for using HydroSight! First off, I see that boreID bore61620102 is not listed in your coordinates file. 
Next, if this problem persists, what version and build date of HydroSight are you using?

**Comment by KongFeihe** [comment]
Thank you very much! But the model crashed always occur, and the version is 1.2.7.
![5](https://user-images.githubusercontent.com/38413487/40095835-9051ca58-58bd-11e8-824c-787d12f57f39.jpg)
![3](https://user-images.githubusercontent.com/38413487/40095840-96697ada-58bd-11e8-8878-b86131c885df.jpg)
![2](https://user-images.githubusercontent.com/38413487/40095841-99aa3022-58bd-11e8-959e-38138bf6b383.jpg)

**Comment by KongFeihe** [comment]
Thank you very much! the three .csv files has been closed, then I restarted the HydroSight and upload the files, it didn't work. I study in Northwest University in China, and my supervisor is Professor Jinxi Song. Now I am a joint Phd supervised by Guobin Fu in CSIRO. 
[bore61710002.zip](https://github.com/peterson-tim-j/HydroSight/files/2007934/bore61710002.zip)

**Comment by KongFeihe** [comment]
Thank you so much, the problem has been addressed, there was something wrong with my forcing data.

**Comment by peterson-tim-j** [comment]
Good to hear. To help other users, could you please summarise how your problem was fixed? Also please consider joining the user group at https://groups.google.com/forum/#!forum/hydrosight
