### ISSUE TITLE
Documentation for the downscaling and in-filling of infrequently metered pumping 

### ISSUE THREAD

**Issue by Cheng168** [peterson-tim-j/HydroSight#35]
Hi Tim, 
Congratulation on the release of the HydroSight version 1.30. 
This is just a question. I am trying to understand the concept of the downscaling and in-filling of infrequently metered pumping in the HydroSight. Have you put the documentation online? 
To my understanding: Firstly the model estimates the average daily pumping rates for the pumping seasons with metered volume using total metered volume, the number of defined pumping days and groundwater hydrograph. Secondly the daily average of all metered seasons is applied to non-metered seasons. For those non-metered seasons, the daily pumping rates are the same. Pump on or off is determined by model calibration. Am I wrong?

**Comment by Cheng168** [comment]
Please see examples of monthly pumping volumes estimated by HydroSight below. 
![examples of monthly pumping volume estimated by hydrosight](https://user-images.githubusercontent.com/26912944/40895990-f9f0b418-67a1-11e8-8b69-3ba82b646aba.JPG)

**Comment by peterson-tim-j** [comment]
Hi Xiang

This issue has prompted me to write a rough first draft wiki explaining the downscaling. See (https://github.com/peterson-tim-j/HydroSight/wiki/Pumping-rate-estimation). Could you let me know if this resolves your issues? Or, raises new concerns?

Cheers

Tim

**Comment by Cheng168** [comment]
As I said, this is a question rather than an issue. The Wiki documentation gives good explanation on the downscaling.
