### ISSUE TITLE
build failed of an example

### ISSUE THREAD

**Issue by KongFeihe** [peterson-tim-j/HydroSight#38]
"Model build failed - Abstract classes cannot be instantiated. Class 'derivedForcing_linearUnconstrainedScaling_dup' inherits abstract methods or properties but does not implement them.  Use meta.abstractDetails to see the list of methods and properties that 'derivedForcing_linearUnconstrainedScaling_dup' must implement if you do not intend the class to be abstract." **_occurred when I try to built the example of TFN model - landuse change with model label  of "Reveg Catchment - Recharge and ET landuse impact" in Graphical User Interface._**
Thank you!
![1](https://user-images.githubusercontent.com/38413487/54658852-6ce1bc00-4b0a-11e9-9f24-2df2fb42b8e1.png)

**Comment by KongFeihe** [comment]
I try the old version-1.27，model build successful, but for 1.30, it build failed.

**Comment by peterson-tim-j** [comment]
Thanks. Does this issue still occur in v1.3.4 (uploaded today)?

**Comment by KongFeihe** [comment]
> Thanks. Does this issue still occur in v1.3.4 (uploaded today)?
Yes, this is still occur in v1.3.4. And when I clicked the 'Models Options' window for the last four line in Graphical User Interface,  Warning Dialog occured 'Unknown model type selected or the Gui for the selected model crashed'.
![TIM截图20190811165014](https://user-images.githubusercontent.com/38413487/62832028-fed59700-bc5a-11e9-99ba-a0dec393dc51.jpg)

**Comment by peterson-tim-j** [comment]
Thanks. This bug was resolved in the commit on 15 Sept 2022.
