### ISSUE TITLE
TFN Model example Failed

### ISSUE THREAD

**Issue by KongFeihe** [peterson-tim-j/HydroSight#39]
when run the sentence "if run7paramModel ...... end", the calibration scheme is unknow. 
![2](https://user-images.githubusercontent.com/38413487/54659221-e037fd80-4b0b-11e9-8472-0a8a2d74afa2.png)

**Comment by peterson-tim-j** [comment]
Thanks for this report. I have fixed this bug and just uploaded it. Can you pls check that this bug is fixed? If so, pls close this comment.

**Comment by KongFeihe** [comment]
Thank You.
