### ISSUE TITLE
output variable name used in example_TFN_model.m

### ISSUE THREAD

**Issue by giancarlo-bonotto** [peterson-tim-j/HydroSight#50]
At example_TFN_model.m, line 72, the output flux option "drainage_normalised" seems to be an invalid output variable name from the forcing transformation function, which stops the algorithm at line 447 of model_TFN.m. Substituting "drainage_normalised" by "drainage" seems to solve it. Thanks

**Comment by peterson-tim-j** [comment]
Thanks. This bug was resolved in the commit on 15 Sept 2022.
