### ISSUE TITLE
number of time-points used in forcingTransform_soilMoisture.c

### ISSUE THREAD

**Issue by giancarlo-bonotto** [peterson-tim-j/HydroSight#52]
Hi Tim. This is not exactly an issue, more a comment. 

Working on HydroSight C and Matlab codes, I've noticed that depending on the path taken to call forcingTransform_soilMoisture.c,  different number of time-points can be used to solve the soil moisture ODEs.

If calling it using the method "get_h_star", which is also called by the methods "objectiveFunction" and "solve",  forcingTransform_soilMoisture.c will use all time-points embedded in the climate-forcing time-series (starting from the latest observed head).  

If calling it directly using the method "setTransformedForcing", forcingTransform_soilMoisture.c will ingest only the time-points that were specified. 

With thanks

**Comment by peterson-tim-j** [comment]
Thanks Giancarlo. Could you pls post a few lines of Matlab code that demonstrate this? - so that I can reproduce the "issue".

**Comment by giancarlo-bonotto** [comment]
Sure. Thanks Tim. =) 

For instance:

>> [head, colnames, noise] = solve(obj, time_points_streamflow)

where 'time_points_streamflow' has say ~4000 date entries corresponding to the period with streamflow observations. In this case, 'solve' ends up calling 'get_h_start' in model_TFN.m which then calls 'setTransformedForcing' to calculate the soil moisture. As 'get_h_start' (lines 2678-2681) adjusts the date entries so it considers all dates contained in 'obj.inputData.forcingData' that are prior to the last date in 'time_points_streamflow', it will give in addition to the ~4000 points in 'setTransformedForcing' all previous dates contained in 'obj.inputData.forcingData', say ~22000 entries. 

Whereas, if i use, say:

>>      setTransformedForcing(obj.parameters.climateTransform_soilMoistureModels_2layer_v2, time_points_streamflow, true);


it will avoid calling 'get_h_start' and will call 'forcingTransform_soilMoisture' considering only the date entries in 'time_points_streamflow'.

**Comment by peterson-tim-j** [comment]
Thanks for the details. I've finally got around to looking into this and forcingTransform_soilMoisture() is only every called from within setTransformedForcing(). Within setTransformedForcing() the time steps are expanded to subdaily (to reduce the estimation of daily soil fluxes) though if forcingTransform_soilMoisture() was instead called from elsewhere then this expansion of the timesteps to subdaily won't occur.

That said, I suspect that this is not the issue you're raising. Any thoughts?
