### ISSUE TITLE
HydroSight functionality on Mac

### ISSUE THREAD

**Issue by henrybennett1** [peterson-tim-j/HydroSight#69]
Hey Tim,

I cant get HydroSight to build on Mac, currently the error states that

Error using movefile
No matching files named '/Users/henrybennett/Desktop/UNI 2024/FYP
Matlab/HydroSight-master/doIRFconvolution.mexa64' were found.

Error in Build_C_code (line 42)
        movefile('doIRFconvolution.mexa64', 'algorithms/models/TransferNoise','f');

I was wondering if you would be able to help with a fix for this?

Thanks,
Henry

**Comment by peterson-tim-j** [comment]
Thanks Henry. I've just pushed an update. 

HydroSight should now be able to compile C code for Mac.
